import {useEffect,useMemo,useState} from 'react';import * as XLSX from 'xlsx';import {supabase} from '../lib/supabase';import {CONFIG} from '../config';
const COLS=[['registration_id','Registration ID'],['team_name','Team Name'],['leader_name','Team Leader Name'],['leader_phone','Leader Number'],['member2_name','Member Name'],['college','College Name'],['robot_name','Robot Name'],['payment_method','Payment Method'],['payment_status','Payment Status'],['razorpay_payment_id','Razorpay Payment ID'],['registered_at','Registration Date'],['payment_received_at','Payment Received Date']];
async function fetchAll(paidOnly){let all=[],from=0;for(;;){let q=supabase.from('registrations').select('*').order('registered_at').range(from,from+999);if(paidOnly)q=q.eq('payment_status','PAID');const {data,error}=await q;if(error)throw error;all=all.concat(data);if(data.length<1000)return all;from+=1000;}}
async function exportXlsx(paidOnly){try{const rows=(await fetchAll(paidOnly)).map(r=>Object.fromEntries(COLS.map(([k,l])=>[l,r[k]??''])));
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Registrations');XLSX.writeFile(wb,`robo-race-2026-${paidOnly?'paid':'all'}-registrations.xlsx`);}catch{alert('Export failed. Please try again.');}}
export default function Admin(){
 const [user,setUser]=useState(null),[ok,setOk]=useState(null),[rows,setRows]=useState([]),[open,setOpen]=useState(false),[q,setQ]=useState(''),[fs,setFs]=useState(''),[fm,setFm]=useState(''),[fc,setFc]=useState(''),[asc,setAsc]=useState(false),[sel,setSel]=useState(null),[err,setErr]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));},[]);
 const load=async()=>{try{const {data:a}=await supabase.from('admins').select('user_id').maybeSingle();if(!a){setOk(false);return;}setOk(true);setRows(await fetchAll(false));const {data:s}=await supabase.from('settings').select('value').eq('key','registration_open').maybeSingle();setOpen(s?.value==='true');}catch{setErr('Could not load data.');}};
 useEffect(()=>{if(user)load();},[user]);
 const view=useMemo(()=>rows.filter(r=>(!fs||r.payment_status===fs)&&(!fm||r.payment_method===fm)&&(!fc||r.college===fc)&&(!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>(asc?1:-1)*(new Date(a.registered_at)-new Date(b.registered_at))),[rows,q,fs,fm,fc,asc]);
 if(!user)return <Login onDone={setUser}/>;
 if(ok===false)return <p className="p-8">This account is not an administrator. <button className="underline" onClick={()=>supabase.auth.signOut().then(()=>setUser(null))}>Sign out</button></p>;
 const paid=rows.filter(r=>r.payment_status==='PAID'),pend=rows.filter(r=>r.payment_status==='PENDING'),fail=rows.filter(r=>r.payment_status==='FAILED');
 const stats=[['TOTAL TEAMS',rows.length],['PAID',paid.length],['PENDING',pend.length],['FAILED',fail.length],['AMOUNT RECEIVED','₹'+paid.reduce((s,r)=>s+r.amount,0)],['EXPECTED (PENDING)','₹'+pend.reduce((s,r)=>s+r.amount,0)],['QUALIFY AFTER R1',Math.ceil(rows.length/2)]];
 const mark=async r=>{if(!confirm(`Mark ₹${r.amount} received from ${r.team_name}?`))return;const {error}=await supabase.from('registrations').update({payment_status:'PAID',amount_collected:r.amount,payment_received_at:new Date().toISOString(),payment_received_by:user.email}).eq('id',r.id);error?alert('Update failed.'):load();};
 const toggle=async()=>{const {error}=await supabase.from('settings').update({value:String(!open)}).eq('key','registration_open');error?alert('Failed.'):setOpen(!open);};
 const colleges=[...new Set(rows.map(r=>r.college))];
 return(<div className="p-4 max-w-7xl mx-auto space-y-4"><div className="flex flex-wrap gap-2 justify-between items-center"><h1 className="font-display text-xl text-cyan-300">ADMIN · {CONFIG.name}</h1>
  <div className="flex flex-wrap gap-2"><button className="btn" onClick={toggle}>{open?'CLOSE REGISTRATION':'OPEN REGISTRATION'}</button><button className="btn" onClick={()=>exportXlsx(false)}>EXPORT ALL REGISTRATIONS</button><button className="btn" onClick={()=>exportXlsx(true)}>EXPORT PAID REGISTRATIONS</button></div></div>
  {err&&<p className="text-red-400">{err}</p>}
  <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3">{stats.map(([l,n])=><div key={l} className="card text-center"><div className="text-xs text-gray-400">{l}</div><div className="font-display text-xl text-amber-400">{n}</div></div>)}</div>
  <div className="flex flex-wrap gap-2"><input className="inp max-w-xs" placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/>
   <select className="inp max-w-40" value={fs} onChange={e=>setFs(e.target.value)}><option value="">All status</option>{['PAID','PENDING','FAILED'].map(s=><option key={s}>{s}</option>)}</select>
   <select className="inp max-w-40" value={fm} onChange={e=>setFm(e.target.value)}><option value="">All methods</option><option>ONLINE</option><option>EVENT_DAY</option></select>
   <select className="inp max-w-52" value={fc} onChange={e=>setFc(e.target.value)}><option value="">All colleges</option>{colleges.map(c=><option key={c}>{c}</option>)}</select></div>
  <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-gray-400"><tr>{['ID','Team','Leader','College','Phone','Robot','Method','Status'].map(h=><th key={h} className="p-2">{h}</th>)}<th className="p-2 cursor-pointer" onClick={()=>setAsc(!asc)}>Date {asc?'↑':'↓'}</th><th/></tr></thead>
  <tbody>{view.map(r=><tr key={r.id} className="border-t border-white/10"><td className="p-2">{r.registration_id}</td><td>{r.team_name}</td><td>{r.leader_name}</td><td>{r.college}</td><td>{r.leader_phone}</td><td>{r.robot_name}</td><td>{r.payment_method}</td><td>{r.payment_status}</td><td>{new Date(r.registered_at).toLocaleDateString('en-IN')}</td>
   <td className="space-x-2 whitespace-nowrap"><button className="underline" onClick={()=>setSel(r)}>View</button>{r.payment_method==='EVENT_DAY'&&r.payment_status==='PENDING'&&<button className="btn !py-1 !px-2 text-xs" onClick={()=>mark(r)}>MARK PAYMENT RECEIVED</button>}</td></tr>)}</tbody></table></div>
  {sel&&<div className="card"><button className="float-right" onClick={()=>setSel(null)}>✕</button>{COLS.map(([k,l])=><p key={k}><span className="text-gray-400">{l}:</span> {String(sel[k]??'—')}</p>)}</div>}</div>);}
function Login({onDone}){const [e,setE]=useState(''),[p,setP]=useState(''),[m,setM]=useState('');
 return <form className="card max-w-sm mx-auto mt-24 grid gap-3" onSubmit={async x=>{x.preventDefault();const {data,error}=await supabase.auth.signInWithPassword({email:e,password:p});error?setM('Invalid login.'):onDone(data.user);}}><h1 className="font-display text-cyan-300">ADMIN LOGIN</h1><input className="inp" type="email" placeholder="Email" value={e} onChange={x=>setE(x.target.value)}/><input className="inp" type="password" placeholder="Password" value={p} onChange={x=>setP(x.target.value)}/>{m&&<p className="text-red-400 text-sm">{m}</p>}<button className="btn">Sign in</button></form>;}
